cc_binary(
    name = "dep-test",
    deps = [
        "@com_github_tgockel_zookeeper_cpp//:zookeeper",
        "@com_github_libuv_libuv//:libuv",
        "@com_github_emilk_loguru//:loguru"
    ],
    srcs = ["main.cpp"]
)